const themes = [
  {
    id: 'dark-editorial',
    name: 'Dark Editorial',
    bestFor: 'Product pitches, investor decks, storytelling',
    fonts: 'Bebas Neue (headings), Crimson Text (body), JetBrains Mono (code)',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Crimson+Text:ital,wght@0,400;0,600;0,700;1,400&family=JetBrains+Mono:wght@400;500&display=swap',
    cssVariables: {
      '--bg': '#ffffff',
      '--bg-warm': '#fafaf8',
      '--bg-card': '#fafaf8',
      '--dark': '#1a1a1a',
      '--text': '#2d2d2d',
      '--text-secondary': '#6b6b6b',
      '--text-muted': '#8a8a7a',
      '--accent': '#d4a847',
      '--accent-light': '#f5e6b8',
      '--accent-bg': '#faf6eb',
      '--secondary': '#c41e3a',
      '--secondary-light': '#fdf2f4',
      '--green': '#2d8a4e',
      '--border': '#e8e4de',
      '--font-title': "'Bebas Neue', 'Arial Black', sans-serif",
      '--font-body': "'Crimson Text', Georgia, serif",
      '--font-mono': "'JetBrains Mono', monospace",
    },
    headingStyle: 'text-transform: uppercase; letter-spacing: 0.04em;',
    listMarkers: 'Gold diamond rotated 45deg',
    closingSlide: 'Dark background (var(--dark)), gold heading',
    designNotes: 'Classic editorial feel with serif body text and bold uppercase headings.',
    designSystem: { palette: { mode: 'light', bg: '#ffffff', text: '#2d2d2d', accent: '#d4a847', secondary: '#c41e3a' }, fonts: { display: 'Bebas Neue', body: 'Crimson Text', mono: 'JetBrains Mono' }, headingStyle: 'uppercase-spaced', radius: 10 },
  },
  {
    id: 'dark-tech',
    name: 'Dark Tech',
    bestFor: 'Engineering talks, technical content, company updates',
    fonts: 'Urbanist (headings), Inter (body)',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Urbanist:wght@400;600;700;800;900&family=Inter:wght@400;500;600;700&display=swap',
    cssVariables: {
      '--bg': '#0a0a0a',
      '--bg-warm': '#141414',
      '--bg-card': '#141414',
      '--dark': '#0a0a0a',
      '--text': '#ffffff',
      '--text-secondary': '#cbd5e1',
      '--text-muted': '#64748b',
      '--accent': '#deff9a',
      '--accent-light': '#deff9a',
      '--accent-bg': 'rgba(222, 255, 154, 0.08)',
      '--secondary': '#60a5fa',
      '--secondary-light': 'rgba(96, 165, 250, 0.1)',
      '--green': '#4ade80',
      '--border': '#1e1e1e',
      '--font-title': "'Urbanist', sans-serif",
      '--font-body': "'Inter', sans-serif",
      '--font-mono': "'JetBrains Mono', monospace",
    },
    headingStyle: 'font-weight: 800;',
    listMarkers: 'Lime green circle',
    closingSlide: 'Lime green heading on dark bg, no inversion needed',
    designNotes: 'Dark mode with lime green accents. Slide transition uses translateX(20px) + opacity.',
    designSystem: { palette: { mode: 'dark', bg: '#0a0a0a', text: '#ffffff', accent: '#deff9a', secondary: '#60a5fa' }, fonts: { display: 'Urbanist', body: 'Inter', mono: 'JetBrains Mono' }, headingStyle: 'bold-clean', radius: 10 },
  },
  {
    id: 'light-mono',
    name: 'Light Mono',
    bestFor: 'Data presentations, status reports, technical deep-dives',
    fonts: 'JetBrains Mono throughout',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,400&display=swap',
    cssVariables: {
      '--bg': '#fafafa',
      '--bg-warm': '#f3f3f3',
      '--bg-card': '#f3f3f3',
      '--dark': '#171717',
      '--text': '#171717',
      '--text-secondary': '#404040',
      '--text-muted': '#a3a3a3',
      '--accent': '#ca8a04',
      '--accent-light': '#fef08a',
      '--accent-bg': '#fef9c3',
      '--secondary': '#171717',
      '--secondary-light': '#f3f3f3',
      '--green': '#22c55e',
      '--border': '#e5e5e5',
      '--font-title': "'JetBrains Mono', monospace",
      '--font-body': "'JetBrains Mono', monospace",
      '--font-mono': "'JetBrains Mono', monospace",
    },
    headingStyle: 'font-weight: 700; text-transform: uppercase; letter-spacing: 0.06em;',
    listMarkers: 'Yellow highlight tags',
    closingSlide: 'Dark bg (var(--dark)), yellow accent heading',
    designNotes: 'All-monospace theme. Prefer data-row grid layout (key-value pairs) over cards for data-dense content.',
    designSystem: { palette: { mode: 'light', bg: '#fafafa', text: '#171717', accent: '#ca8a04', secondary: '#171717' }, fonts: { display: 'JetBrains Mono', body: 'JetBrains Mono', mono: 'JetBrains Mono' }, headingStyle: 'uppercase-spaced', radius: 10 },
  },
  {
    id: 'minimal-light',
    name: 'Minimal Light',
    bestFor: 'General presentations, training, external audiences',
    fonts: 'Inter (headings + body)',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap',
    cssVariables: {
      '--bg': '#ffffff',
      '--bg-warm': '#f8fafc',
      '--bg-card': '#f8fafc',
      '--dark': '#0f172a',
      '--text': '#1e293b',
      '--text-secondary': '#475569',
      '--text-muted': '#94a3b8',
      '--accent': '#2563eb',
      '--accent-light': '#dbeafe',
      '--accent-bg': '#eff6ff',
      '--secondary': '#7c3aed',
      '--secondary-light': '#f5f3ff',
      '--green': '#16a34a',
      '--border': '#e2e8f0',
      '--font-title': "'Inter', sans-serif",
      '--font-body': "'Inter', sans-serif",
      '--font-mono': "'JetBrains Mono', monospace",
    },
    headingStyle: 'font-weight: 700;',
    listMarkers: 'Blue circle',
    closingSlide: 'Dark navy bg (var(--dark)), white heading, blue accent',
    designNotes: 'Clean, no uppercase headings. Good default for any presentation.',
    designSystem: { palette: { mode: 'light', bg: '#ffffff', text: '#1e293b', accent: '#2563eb', secondary: '#7c3aed' }, fonts: { display: 'Inter', body: 'Inter', mono: 'JetBrains Mono' }, headingStyle: 'bold-clean', radius: 10 },
  },
  {
    id: 'corporate-blue',
    name: 'Corporate Blue',
    bestFor: 'Corporate presentations, board meetings, business proposals',
    fonts: 'Inter (headings), Source Sans 3 (body)',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Source+Sans+3:wght@300;400;500;600;700&display=swap',
    cssVariables: {
      '--bg': '#f8fbff',
      '--bg-warm': '#f0f4fa',
      '--bg-card': '#ffffff',
      '--dark': '#0c1b33',
      '--text': '#1e2a3a',
      '--text-secondary': '#4a5e78',
      '--text-muted': '#8b9bb5',
      '--accent': '#2563eb',
      '--accent-light': '#bfdbfe',
      '--accent-bg': '#eff6ff',
      '--secondary': '#0f766e',
      '--secondary-light': '#f0fdfa',
      '--green': '#16a34a',
      '--border': '#d5e2f0',
      '--font-title': "'Inter', sans-serif",
      '--font-body': "'Source Sans 3', sans-serif",
      '--font-mono': "'JetBrains Mono', monospace",
    },
    headingStyle: 'font-weight: 700; letter-spacing: -0.01em;',
    listMarkers: 'Blue square',
    closingSlide: 'Dark navy bg (var(--dark)), white heading, blue accent bar',
    designNotes: 'Professional corporate look with blue tones and readable body font.',
    designSystem: { palette: { mode: 'light', bg: '#f8fbff', text: '#1e2a3a', accent: '#2563eb', secondary: '#0f766e' }, fonts: { display: 'Inter', body: 'Source Sans 3', mono: 'JetBrains Mono' }, headingStyle: 'bold-clean', radius: 10 },
  },
  {
    id: 'warm-earth',
    name: 'Warm Earth',
    bestFor: 'Sustainability, wellness, organic brands, lifestyle pitches',
    fonts: 'Lora (headings), Nunito (body)',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400&family=Nunito:wght@300;400;500;600;700&display=swap',
    cssVariables: {
      '--bg': '#f7f1e8',
      '--bg-warm': '#f2ead8',
      '--bg-card': '#fdf9f2',
      '--dark': '#2c1d0e',
      '--text': '#3d2e1f',
      '--text-secondary': '#6b5740',
      '--text-muted': '#a08b6d',
      '--accent': '#c96f4a',
      '--accent-light': '#f5d4c2',
      '--accent-bg': '#fdf0e8',
      '--secondary': '#8b5e34',
      '--secondary-light': '#f5ead8',
      '--green': '#5a7a3a',
      '--border': '#e0d4c0',
      '--font-title': "'Lora', serif",
      '--font-body': "'Nunito', sans-serif",
      '--font-mono': "'JetBrains Mono', monospace",
    },
    headingStyle: 'font-weight: 600; font-style: italic;',
    listMarkers: 'Terracotta leaf',
    closingSlide: 'Deep brown bg (var(--dark)), cream heading, terracotta accent line',
    designNotes: 'Warm, organic palette with serif headings and rounded sans-serif body.',
    designSystem: { palette: { mode: 'light', bg: '#f7f1e8', text: '#3d2e1f', accent: '#c96f4a', secondary: '#8b5e34' }, fonts: { display: 'Lora', body: 'Nunito', mono: 'JetBrains Mono' }, headingStyle: 'weighted-clean', radius: 10 },
  },
  {
    id: 'neon-noir',
    name: 'Neon Noir',
    bestFor: 'Gaming, cyberpunk, tech demos, hackathon presentations',
    fonts: 'Orbitron (headings), Rajdhani (body)',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Orbitron:wght@400;500;600;700;800;900&family=Rajdhani:wght@300;400;500;600;700&display=swap',
    cssVariables: {
      '--bg': '#0b1020',
      '--bg-warm': '#0f1528',
      '--bg-card': '#131a2e',
      '--dark': '#060810',
      '--text': '#e0e6f0',
      '--text-secondary': '#a0aec0',
      '--text-muted': '#5a6578',
      '--accent': '#ff4fd8',
      '--accent-light': '#ff4fd840',
      '--accent-bg': '#ff4fd815',
      '--secondary': '#22d3ee',
      '--secondary-light': '#22d3ee20',
      '--green': '#4ade80',
      '--border': '#1e2a44',
      '--font-title': "'Orbitron', sans-serif",
      '--font-body': "'Rajdhani', sans-serif",
      '--font-mono': "'JetBrains Mono', monospace",
    },
    headingStyle: 'text-transform: uppercase; letter-spacing: 0.08em; font-weight: 700;',
    listMarkers: 'Neon pink arrow',
    closingSlide: 'Deep dark bg (var(--dark)), neon pink heading with glow effect, cyan accent line',
    designNotes: 'Cyberpunk aesthetic with neon pink and cyan on deep navy. Bold geometric headings.',
    designSystem: { palette: { mode: 'dark', bg: '#0b1020', text: '#e0e6f0', accent: '#ff4fd8', secondary: '#22d3ee' }, fonts: { display: 'Orbitron', body: 'Rajdhani', mono: 'JetBrains Mono' }, headingStyle: 'uppercase-spaced', radius: 10 },
  },
  {
    id: 'paper-ink',
    name: 'Paper & Ink',
    bestFor: 'Academic papers, literary presentations, book launches, journalism',
    fonts: 'Playfair Display (headings), Lato (body)',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,700&family=Lato:ital,wght@0,300;0,400;0,700;1,400&display=swap',
    cssVariables: {
      '--bg': '#fcf8ef',
      '--bg-warm': '#f7f0e0',
      '--bg-card': '#fefcf5',
      '--dark': '#1c1a16',
      '--text': '#2e2b24',
      '--text-secondary': '#5c574a',
      '--text-muted': '#8c8576',
      '--accent': '#8b6f47',
      '--accent-light': '#dcc9a3',
      '--accent-bg': '#f5eed8',
      '--secondary': '#3f5c7a',
      '--secondary-light': '#e8eff5',
      '--green': '#4d7a3e',
      '--border': '#ddd5c4',
      '--font-title': "'Playfair Display', Georgia, serif",
      '--font-body': "'Lato', sans-serif",
      '--font-mono': "'JetBrains Mono', monospace",
    },
    headingStyle: 'font-weight: 700; font-style: italic;',
    listMarkers: 'Ink-colored em dash',
    closingSlide: 'Dark parchment bg (var(--dark)), cream heading, ink accent underline',
    designNotes: 'Elegant editorial feel on warm parchment. Italic serif headings with clean sans-serif body.',
    designSystem: { palette: { mode: 'light', bg: '#fcf8ef', text: '#2e2b24', accent: '#8b6f47', secondary: '#3f5c7a' }, fonts: { display: 'Playfair Display', body: 'Lato', mono: 'JetBrains Mono' }, headingStyle: 'weighted-clean', radius: 10 },
  },
  {
    id: 'ocean-depth',
    name: 'Ocean Depth',
    bestFor: 'Marine, science, deep tech, data-driven presentations',
    fonts: 'Space Grotesk (headings), DM Sans (body)',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400&display=swap',
    cssVariables: {
      '--bg': '#071c2c',
      '--bg-warm': '#0a2438',
      '--bg-card': '#0d2a42',
      '--dark': '#030e18',
      '--text': '#d4e5f7',
      '--text-secondary': '#8db3d4',
      '--text-muted': '#4d7a9e',
      '--accent': '#14b8a6',
      '--accent-light': '#14b8a640',
      '--accent-bg': '#14b8a615',
      '--secondary': '#3b82f6',
      '--secondary-light': '#3b82f620',
      '--green': '#34d399',
      '--border': '#163a54',
      '--font-title': "'Space Grotesk', sans-serif",
      '--font-body': "'DM Sans', sans-serif",
      '--font-mono': "'JetBrains Mono', monospace",
    },
    headingStyle: 'font-weight: 700; letter-spacing: -0.02em;',
    listMarkers: 'Teal circle',
    closingSlide: 'Deepest navy bg (var(--dark)), teal heading, blue accent wave',
    designNotes: 'Deep ocean palette with teal accents. Modern geometric headings.',
    designSystem: { palette: { mode: 'dark', bg: '#071c2c', text: '#d4e5f7', accent: '#14b8a6', secondary: '#3b82f6' }, fonts: { display: 'Space Grotesk', body: 'DM Sans', mono: 'JetBrains Mono' }, headingStyle: 'bold-clean', radius: 10 },
  },
  {
    id: 'sunset-gradient',
    name: 'Sunset Gradient',
    bestFor: 'Creative agencies, event decks, lifestyle brands, marketing',
    fonts: 'Poppins (headings), Quicksand (body)',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,400&family=Quicksand:wght@300;400;500;600;700&display=swap',
    cssVariables: {
      '--bg': '#fff7ed',
      '--bg-warm': '#fff1df',
      '--bg-card': '#fffbf5',
      '--dark': '#2d1208',
      '--text': '#3c1f0e',
      '--text-secondary': '#7a5233',
      '--text-muted': '#b08a60',
      '--accent': '#f97316',
      '--accent-light': '#fed7aa',
      '--accent-bg': '#fff7ed',
      '--secondary': '#f59e0b',
      '--secondary-light': '#fef9c3',
      '--green': '#65a30d',
      '--border': '#f0d9be',
      '--font-title': "'Poppins', sans-serif",
      '--font-body': "'Quicksand', sans-serif",
      '--font-mono': "'JetBrains Mono', monospace",
    },
    headingStyle: 'font-weight: 700;',
    listMarkers: 'Orange sun',
    closingSlide: 'Deep warm brown bg (var(--dark)), amber heading, orange accent',
    designNotes: 'Warm sunset tones with rounded, friendly typography.',
    designSystem: { palette: { mode: 'light', bg: '#fff7ed', text: '#3c1f0e', accent: '#f97316', secondary: '#f59e0b' }, fonts: { display: 'Poppins', body: 'Quicksand', mono: 'JetBrains Mono' }, headingStyle: 'bold-clean', radius: 10 },
  },
  {
    id: 'arctic-frost',
    name: 'Arctic Frost',
    bestFor: 'Clean SaaS, health tech, fintech, professional services',
    fonts: 'Outfit (headings), Manrope (body)',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&family=Manrope:wght@300;400;500;600;700;800&display=swap',
    cssVariables: {
      '--bg': '#f8fbff',
      '--bg-warm': '#eef4fb',
      '--bg-card': '#ffffff',
      '--dark': '#0c1929',
      '--text': '#1a2b40',
      '--text-secondary': '#4b6382',
      '--text-muted': '#8fa4be',
      '--accent': '#60a5fa',
      '--accent-light': '#bfdbfe',
      '--accent-bg': '#eff6ff',
      '--secondary': '#38bdf8',
      '--secondary-light': '#e0f2fe',
      '--green': '#34d399',
      '--border': '#d4e4f4',
      '--font-title': "'Outfit', sans-serif",
      '--font-body': "'Manrope', sans-serif",
      '--font-mono': "'JetBrains Mono', monospace",
    },
    headingStyle: 'font-weight: 700; letter-spacing: -0.01em;',
    listMarkers: 'Ice blue circle',
    closingSlide: 'Dark navy bg (var(--dark)), ice blue heading, frost accent gradient',
    designNotes: 'Cool, crisp palette with modern geometric typography. Professional and clean.',
    designSystem: { palette: { mode: 'light', bg: '#f8fbff', text: '#1a2b40', accent: '#60a5fa', secondary: '#38bdf8' }, fonts: { display: 'Outfit', body: 'Manrope', mono: 'JetBrains Mono' }, headingStyle: 'bold-clean', radius: 10 },
  },
  {
    id: 'forest-canopy',
    name: 'Forest Canopy',
    bestFor: 'Environmental, outdoor brands, nature documentaries, NGOs',
    fonts: 'Bitter (headings), Work Sans (body)',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Bitter:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400&family=Work+Sans:wght@300;400;500;600;700&display=swap',
    cssVariables: {
      '--bg': '#10231c',
      '--bg-warm': '#152e24',
      '--bg-card': '#1a382c',
      '--dark': '#0a1610',
      '--text': '#d4e6d8',
      '--text-secondary': '#8fb89a',
      '--text-muted': '#4e7a5a',
      '--accent': '#d4a373',
      '--accent-light': '#d4a37340',
      '--accent-bg': '#d4a37315',
      '--secondary': '#4f772d',
      '--secondary-light': '#4f772d30',
      '--green': '#86efac',
      '--border': '#243d30',
      '--font-title': "'Bitter', serif",
      '--font-body': "'Work Sans', sans-serif",
      '--font-mono': "'JetBrains Mono', monospace",
    },
    headingStyle: 'font-weight: 700;',
    listMarkers: 'Gold leaf',
    closingSlide: 'Deepest forest bg (var(--dark)), gold heading, green accent underline',
    designNotes: 'Dark forest palette with warm gold accents. Serif headings for gravitas.',
    designSystem: { palette: { mode: 'dark', bg: '#10231c', text: '#d4e6d8', accent: '#d4a373', secondary: '#4f772d' }, fonts: { display: 'Bitter', body: 'Work Sans', mono: 'JetBrains Mono' }, headingStyle: 'bold-clean', radius: 10 },
  },
  {
    id: 'slate-rose',
    name: 'Slate Rose',
    bestFor: 'Fashion, beauty, luxury brands, portfolio decks',
    fonts: 'Sora (headings), Archivo (body)',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Sora:wght@300;400;500;600;700;800&family=Archivo:ital,wght@0,400;0,500;0,600;0,700;1,400&display=swap',
    cssVariables: {
      '--bg': '#1b1d27',
      '--bg-warm': '#21232f',
      '--bg-card': '#262838',
      '--dark': '#12131a',
      '--text': '#e2dfe8',
      '--text-secondary': '#a09db5',
      '--text-muted': '#5e5b72',
      '--accent': '#f472b6',
      '--accent-light': '#f472b640',
      '--accent-bg': '#f472b615',
      '--secondary': '#a78bfa',
      '--secondary-light': '#a78bfa20',
      '--green': '#4ade80',
      '--border': '#2e3044',
      '--font-title': "'Sora', sans-serif",
      '--font-body': "'Archivo', sans-serif",
      '--font-mono': "'JetBrains Mono', monospace",
    },
    headingStyle: 'font-weight: 700; letter-spacing: -0.02em;',
    listMarkers: 'Rose pink circle',
    closingSlide: 'Deep slate bg (var(--dark)), rose pink heading, lavender accent line',
    designNotes: 'Dark slate with rose pink and lavender. Modern, fashion-forward feel.',
    designSystem: { palette: { mode: 'dark', bg: '#1b1d27', text: '#e2dfe8', accent: '#f472b6', secondary: '#a78bfa' }, fonts: { display: 'Sora', body: 'Archivo', mono: 'JetBrains Mono' }, headingStyle: 'bold-clean', radius: 10 },
  },
  {
    id: 'retro-terminal',
    name: 'Retro Terminal',
    bestFor: 'Developer talks, CLI tool demos, retro/nostalgic tech, hacker culture',
    fonts: 'Fira Code (headings + body + code)',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Fira+Code:wght@300;400;500;600;700&display=swap',
    cssVariables: {
      '--bg': '#020402',
      '--bg-warm': '#071207',
      '--bg-card': '#0c1a0c',
      '--dark': '#000000',
      '--text': '#ccf5cc',
      '--text-secondary': '#7abf7a',
      '--text-muted': '#3d6b3d',
      '--accent': '#5fff87',
      '--accent-light': '#5fff8740',
      '--accent-bg': '#5fff8712',
      '--secondary': '#2bdc74',
      '--secondary-light': '#2bdc7420',
      '--green': '#5fff87',
      '--border': '#1a3a1a',
      '--font-title': "'Fira Code', monospace",
      '--font-body': "'Fira Code', monospace",
      '--font-mono': "'JetBrains Mono', monospace",
    },
    headingStyle: 'text-transform: uppercase; letter-spacing: 0.06em; font-weight: 700;',
    listMarkers: 'Green caret (>)',
    closingSlide: 'Pure black bg (var(--dark)), green phosphor heading with scanline effect, blinking cursor',
    designNotes: 'CRT-style green-on-black terminal aesthetic. All-monospace with phosphor glow.',
    designSystem: { palette: { mode: 'dark', bg: '#020402', text: '#ccf5cc', accent: '#5fff87', secondary: '#2bdc74' }, fonts: { display: 'Fira Code', body: 'Fira Code', mono: 'JetBrains Mono' }, headingStyle: 'uppercase-spaced', radius: 10 },
  },
  {
    id: 'sand-stone',
    name: 'Sand Stone',
    bestFor: 'Architecture, interior design, real estate, heritage brands',
    fonts: 'Cormorant Garamond (headings), Karla (body)',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;0,700;1,400;1,700&family=Karla:ital,wght@0,300;0,400;0,500;0,700;1,400&display=swap',
    cssVariables: {
      '--bg': '#f8f1e7',
      '--bg-warm': '#f0e6d4',
      '--bg-card': '#fcf7ef',
      '--dark': '#2a1f14',
      '--text': '#3a2e22',
      '--text-secondary': '#6d5d4a',
      '--text-muted': '#a39280',
      '--accent': '#c78b4a',
      '--accent-light': '#e8c89a',
      '--accent-bg': '#f8f0e0',
      '--secondary': '#8c6a43',
      '--secondary-light': '#f2e4d0',
      '--green': '#6b8e3a',
      '--border': '#ddd0be',
      '--font-title': "'Cormorant Garamond', Georgia, serif",
      '--font-body': "'Karla', sans-serif",
      '--font-mono': "'JetBrains Mono', monospace",
    },
    headingStyle: 'font-weight: 600; letter-spacing: 0.02em;',
    listMarkers: 'Sandstone dot',
    closingSlide: 'Deep sandstone bg (var(--dark)), warm gold heading, stone accent line',
    designNotes: 'Warm sandstone palette with elegant serif headings. Architectural, refined.',
    designSystem: { palette: { mode: 'light', bg: '#f8f1e7', text: '#3a2e22', accent: '#c78b4a', secondary: '#8c6a43' }, fonts: { display: 'Cormorant Garamond', body: 'Karla', mono: 'JetBrains Mono' }, headingStyle: 'weighted-clean', radius: 10 },
  },
  {
    id: 'data-terminal',
    name: 'Data Terminal',
    bestFor: 'Case studies, frameworks, data-dense reports, HR/org analysis, research presentations',
    fonts: 'JetBrains Mono throughout (all-monospace, like a terminal readout)',
    googleFontsUrl:
      'https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,400&display=swap',
    cssVariables: {
      '--bg': '#fafafa',
      '--bg-warm': '#f3f3f3',
      '--bg-card': '#f3f3f3',
      '--dark': '#171717',
      '--text': '#171717',
      '--text-secondary': '#404040',
      '--text-muted': '#a3a3a3',
      '--text-faint': '#c5c5c5',
      '--accent': '#ca8a04',
      '--accent-light': '#fef08a',
      '--accent-bg': '#fef9c3',
      '--secondary': '#171717',
      '--secondary-light': '#f3f3f3',
      '--green': '#22c55e',
      '--border': '#e5e5e5',
      '--border-strong': '#d0d0d0',
      '--font-title': "'JetBrains Mono', monospace",
      '--font-body': "'JetBrains Mono', monospace",
      '--font-mono': "'JetBrains Mono', monospace",
    },
    headingStyle: 'font-weight: 700; letter-spacing: -0.03em;',
    listMarkers: 'Yellow highlight tags (.tag with yellow bg)',
    closingSlide: 'Dark bg (var(--dark)), yellow accent heading',
    designNotes:
      'Data-dense terminal readout style. Features green terminal prompts ($ query --level 3), ' +
      'data-row grids (2-column key-value pairs), split-panel slides (1fr 1fr), ' +
      'diagnostic/verdict boxes (yellow/green/amber), blinking cursor on title slide, ' +
      'dot navigation (square dots), and grayscale photo treatment. ' +
      'Similar to light-mono but with richer data visualization patterns.',
    designSystem: { palette: { mode: 'light', bg: '#fafafa', text: '#171717', accent: '#ca8a04', secondary: '#171717' }, fonts: { display: 'JetBrains Mono', body: 'JetBrains Mono', mono: 'JetBrains Mono' }, headingStyle: 'tight-dense', radius: 2 },
  },
  {
    id: 'google-design',
    name: 'Google Design',
    bestFor: 'Google partnership pitches, Material Design presentations, AI/ML demos, tech product showcases',
    fonts: 'Plus Jakarta Sans (headings), Inter (body), JetBrains Mono (code)',
    googleFontsUrl: 'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500&family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap',
    cssVariables: {
      '--bg': '#f8f9fa',
      '--bg-warm': '#f3f4f5',
      '--bg-card': '#ffffff',
      '--dark': '#191c1d',
      '--text': '#202124',
      '--text-secondary': '#5f6368',
      '--text-muted': '#9aa0a6',
      '--accent': '#0058bd',
      '--accent-light': '#d8e2ff',
      '--accent-bg': 'rgba(0, 88, 189, 0.05)',
      '--secondary': '#34A853',
      '--secondary-light': 'rgba(52, 168, 83, 0.1)',
      '--green': '#34A853',
      '--border': '#e1e3e4',
      '--font-title': "'Plus Jakarta Sans', sans-serif",
      '--font-body': "'Inter', sans-serif",
      '--font-mono': "'JetBrains Mono', monospace",
    },
    headingStyle: 'font-weight: 700; letter-spacing: -0.025em;',
    listMarkers: 'Blue filled circle',
    closingSlide: 'Light wash bg (subtle gradient to accent tint), blue heading, glass-card contact bar',
    designNotes:
      'Material Design 3 inspired. Features glass cards (backdrop-filter: blur(12px)), ' +
      'Gemini gradient accent (linear-gradient(135deg, #FFBB00, #E244D1, #4285F4)) for hero text and progress bar, ' +
      'Google brand colors (red #EA4335, yellow #FBBC04, green #34A853, blue #4285F4) for category accents, ' +
      'pill badges with mono uppercase labels, stat cards with large numbers, ' +
      'connecting-line architecture diagrams, floating hero icon animation, ' +
      'Material Symbols Outlined icons, bottom navigation bar with slide counter, ' +
      'and safe-area support for mobile.',
    designSystem: { palette: { mode: 'light', bg: '#f8f9fa', text: '#202124', accent: '#0058bd', secondary: '#34A853' }, fonts: { display: 'Plus Jakarta Sans', body: 'Inter', mono: 'JetBrains Mono' }, headingStyle: 'bold-clean', radius: 12 },
  },
];

module.exports = themes;
